front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

#通道
front_channel:
    path: /channel.api
    defaults: { _controller: FrontBundle:Channel:index }

#商户
front_shanghu:
    path: /shanghu.api
    defaults: { _controller: FrontBundle:Shanghu:index }

#订单
front_order:
    path:     /order.api
    defaults: { _controller: FrontBundle:Order:index }

#代收
front_payin_api:
    path:     /payin.api
    defaults: { _controller: FrontBundle:Payin:index }

#代付
front_payout_api:
    path:     /payout.api
    defaults: { _controller: FrontBundle:Payout:index }

#统计
front_statistics:
    path:     /statistics.api
    defaults: { _controller: FrontBundle:Statistics:index }

#日志
front_log:
    path:     /log.api
    defaults: { _controller: FrontBundle:Log:index }
    
#上分 下分
front_dispatch:
    path:     /dispatch.api
    defaults: { _controller: FrontBundle:Dispatch:index }
    
###################################
## react
###################################
react_channel_index:
    path:     /channel_index
    defaults: { _controller: FrontBundle:Default:index }
react_merchant_index:
    path:     /merchant_index
    defaults: { _controller: FrontBundle:Default:index }
react_data_orderin:
    path:     /data_orderin
    defaults: { _controller: FrontBundle:Default:index }
react_data_orderout:
    path:     /data_orderout
    defaults: { _controller: FrontBundle:Default:index }
react_log:
    path:     /log
    defaults: { _controller: FrontBundle:Default:index }
react_dispatch_withdrawal:
    path:     /dispatch_withdrawal
    defaults: { _controller: FrontBundle:Default:index }
react_dispatch_topup:
    path:     /dispatch_topup
    defaults: { _controller: FrontBundle:Default:index }
react_data_statistics:
    path:     /data_statistics
    defaults: { _controller: FrontBundle:Default:index }













