front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

#首页
front_home:
    path:     /home
    defaults: { _controller: FrontBundle:Home:index }

#统计
front_tongji:
    path:     /tongji
    defaults: { _controller: FrontBundle:Tongji:index }

#商户
front_merchant:
    path:     /merchant
    defaults: { _controller: FrontBundle:Merchant:index }    
 
#渠道
front_channel:
    path:     /channel
    defaults: { _controller: FrontBundle:Channel:index }

#代收订单
front_order:
    path:     /order
    defaults: { _controller: FrontBundle:Order:index }

#代付
front_pay:
    path:     /pay
    defaults: { _controller: FrontBundle:Pay:index }

#代理
front_proxy:
    path:     /proxy
    defaults: { _controller: FrontBundle:Proxy:index }

#提现
front_tixian:
    path:     /tixian
    defaults: { _controller: FrontBundle:Tixian:index }

#充值
front_chongzhi:
    path:     /chongzhi
    defaults: { _controller: FrontBundle:Chongzhi:index }

#用户管理
front_account:
    path:     /account
    defaults: { _controller: FrontBundle:Account:index }



















