front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

#通道
front_channel:
    path: /channel.api
    defaults: { _controller: FrontBundle:Channel:index }

#商户
front_shanghu:
    path: /shanghu.api
    defaults: { _controller: FrontBundle:Shanghu:index }

###################################
## react
###################################
react_channel_index:
    path:     /channel_index
    defaults: { _controller: FrontBundle:Default:index }
react_merchant_index:
    path:     /merchant_index
    defaults: { _controller: FrontBundle:Default:index }


