front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

#通道
front_channel:
    path: /channel.api
    defaults: { _controller: FrontBundle:Channel:index }

#商户
front_shanghu:
    path: /shanghu.api
    defaults: { _controller: FrontBundle:Shanghu:index }

