# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    twig.front_extension:
        class: FrontBundle\Twig\FrontExtension
        tags:
            - { name: twig.extension }
 