(function(){function l(a){return document.getElementById(a)}function I(a){if(document.querySelectorAll)return document.querySelectorAll("."+a);var c=[];a=RegExp("(//s|^)"+a+"($|//s)");for(var b=document.getElementsByTagName("*"),k=0;k<b.length;k++)a.test(b[k].className)&&c.push(b[k]);return c}function n(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent?a.attachEvent("on"+c,b):a["on"+c]=b}function O(){var a=window.innerHeight;"number"!=typeof a&&(a="CSS1Compat"==document.compatMode?
document.documentElement.clientHeight:document.body.clientHeight);return a}function P(){var a=window.innerWidth;"number"!=typeof a&&(a="CSS1Compat"==document.compatMode?document.documentElement.clientWidth:document.body.clientWidth);return a}var D=/msie 6/i.test(navigator.userAgent);Array.prototype.map||(Array.prototype.map=function(a,c){var b,k,h;if(null==this)return!1;var g=Object(this),p=g.length>>>0;if("[object Function]"!={}.toString.call(a))return!1;c&&(b=c);k=Array(p);for(h=0;h<p;){var d,f;
h in g&&(d=g[h],f=a.call(b,d,h,g),k[h]=f);h++}return k});window.jQueryproduct=function(a){n(window,"load",a)};window.jsproduct={addFavorite:function(a){var c=a.url?"http://"+a.url:location.href,b=a.title;(a=l(a.id))&&n(a,"click",function(){try{window.external.addFavorite(c,b)}catch(a){try{window.sidebar.addPanel(b,c,"")}catch(h){}}return!1})},setHomePage:function(a){var c=a.url?"http://"+a.url:location.href;(a=l(a.id))&&n(a,"click",function(){document.all&&(document.body.style.behavior="url(#default#homepage)",
document.body.setHomePage(c));return!1})},fixPng:function(a){D&&I(a.cls).map(function(a){var b=a.src.toUpperCase();if("PNG"==b.substring(b.length-3,b.length)){var b=a.id?"id='"+a.id+"'":"",k=a.className?"class='"+a.className+"' ":"",h=a.title?"title='"+a.title+"' ":"title='"+a.alt+"' ",g="display:inline-block;"+a.style.cssText;a.parentElement.href&&(g="cursor:hand;"+g);a.outerHTML="<span "+b+k+h+' style="width:'+a.width+"px; height:"+a.height+"px;"+g+"filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
a.src+"', sizingMethod='scale');\"></span>"}})},floatDiv:function(a){function c(a){clearInterval(f);f=setInterval(function(){var c=(b.offsetLeft-a)/5,c=0<c?Math.ceil(c):Math.floor(c);b.offsetLeft==a?clearInterval(f):b.style.left=b.offsetLeft-c+"px"},30)}var b=l(a.id),k=parseInt(a.top,10),h=P(),g=0,p=0,d=0,f=null,m=document.body.offsetHeight>=O()?15:0;b.style.position=D?"absolute":"fixed";b.style.top=k+"px";a.left?(d=parseInt(a.left,10),b.style.left=d+"px",g=0,p=d):(d=parseInt(a.right,10),b.style.right=
d+"px",g=h-b.offsetWidth-m,p=h+d);0>d&&(n(b,"mouseover",function(){c(g)}),n(b,"mouseout",function(){c(p)}));D&&n(window,"scroll",function(){clearTimeout(a);var a=setTimeout(function(){b.style.top=(document.documentElement.scrollTop||document.body.scrollTop)+k+"px"},1)})},linkage:function(a){for(var c=a.data,b=l(a.id1),k=l(a.id2),h,g,p,d,f=0;f<c[0].length;f++)h=new Option(c[0][f],c[0][f]),k.add(h,void 0);n(b,"change",function(){g=b.options[b.selectedIndex].index;p=c[g];d=k.options.length;for(f=0;f<
c[g].length;f++)h=new Option(p[f],p[f]),k.add(h,void 0);for(f=0;f<d;f++)k.remove(0)})},tab:function(a){var c=a.btns,b=a.tabs,k=null,h=a.activeClassName,g=a.eventType||1,p=null,d=a.delay||150;switch(g){case 1:g="mouseover";break;case 2:g="click"}for(a=0;a<c.length;a++)l(b[a]).style.display="none",n(l(c[a]),g,function(a){return function(){clearTimeout(k);k=setTimeout(function(){for(var d=0;d<c.length;d++)a==d?(l(c[d]).className+=" "+h,l(b[d]).style.display="block"):(p=eval("/(^"+h+")|((\\s)"+h+")/g"),
l(c[d]).className=l(c[d]).className.replace(p,""),l(b[d]).style.display="none");return!1},d)}}(a));l(b[0]).style.display="block"},downMenu:function(a){for(var c=l(a.id),b=(a.pElement||"LI").toUpperCase(),k=(a.cElement||"UL").toUpperCase(),h=a.cls,g=c.getElementsByTagName(b),c=0;c<g.length;c++)n(g[c],"mouseover",function(c){return function(){g[c].parentNode.parentNode.id!=a.id&&(g[c].parentNode.parentNode.className=h);for(var b=g[c].childNodes,f=0;f<b.length;f++)b[f].tagName==k&&(b[f].style.display=
"block")}}(c)),n(g[c],"mouseout",function(c){return function(){g[c].parentNode.parentNode.id!=a.id&&(g[c].parentNode.parentNode.className="");for(var b=g[c].childNodes,f=0;f<b.length;f++)b[f].tagName==k&&(b[f].style.display="none")}}(c))},scroll:function(a){function c(){"top"===u||"left"===u?k():("bottom"===u||"right"===u)&&b()}function b(){d.insertBefore(m[m.length-1],d.firstChild);d.style[y]=-E+"px";h(0)}function k(){h(-E,function(){d.appendChild(m[0]);d.style[y]="0px"})}function h(a,c){clearInterval(x);
x=setInterval(function(){var b=(a-d[z]+f)/5,b=0<b?Math.ceil(b):Math.floor(b);a+f==d[z]?(clearInterval(x),c&&c.apply(g)):d.style[y]=b+d[z]-f+"px"},30)}if(!a.box||!a.list)return!1;var g=this,p=l(a.box),d=l(a.list),f=0,m=d.children,A=a.Automatic||"auto",x=null,r=null,E=0,u=a.direction||"top",y="top",z="offsetTop",B=l(a.advanceArrow),w=l(a.retreatArrow),v=a.spacing||4E3;p.style.position="relative";d.style.position="relative";if("top"===u||"bottom"===u)E=m[1].offsetTop-m[0].offsetTop,y="top",f=d.offsetTop,
z="offsetTop";else if("left"===u||"right"===u)E=m[1].offsetLeft-m[0].offsetLeft,y="left",f=d.offsetLeft,z="offsetLeft";B&&n(B,"click",function(){clearInterval(r);b();r=setInterval(function(){"auto"==A&&c()},v)});w&&n(w,"click",function(){clearInterval(r);k();r=setInterval(function(){"auto"==A&&c()},v)});r=setInterval(function(){"auto"==A&&c()},v);n(d,"mouseover",function(){clearInterval(r)});n(d,"mouseout",function(){r=setInterval(function(){"auto"==A&&c()},v)})},slider:function(a){function c(){var a=
document.createElement("div");a.style.overflow="hidden";a.id=C;a.innerHTML=x[0].title;f.appendChild(a)}function b(a){clearInterval(J);clearInterval(K);var b=l(C);if(!b)return!1;J=setInterval(function(){b.style.height=b.offsetHeight-Math.ceil(b.offsetHeight/5)+"px";0==b.offsetHeight&&(clearInterval(J),b.innerHTML=x[a].title,K=setInterval(function(){b.style.height=b.offsetHeight+Math.ceil((L-b.offsetHeight)/5)+"px";b.offsetHeight>=L&&clearInterval(K)},20))},30)}function k(a){for(var b=0;b<F.length;b++)F[b].className=
a===b?M:""}function h(a,b){switch(a){case 1:g(b);break;case 2:p(b);break;default:p(b)}}function g(a,b){var c=-y*a;clearInterval(D);D=setInterval(function(){var a=(c-m[B]+G)/5,a=0<a?Math.ceil(a):Math.floor(a);c+G==m[B]?(clearInterval(D),b&&b.apply(d)):m.style[z]=a+m[B]-G+"px"},30)}function p(a){var b=x[0],c;b.style.opacity=0;b.style.filter="alpha(opacity=0);";b.src=E[a];0<r.length&&(r[0].href=u[a]);var d=setInterval(function(){c=parseInt(100*(b.style.opacity||0));speed=Math.ceil((100-c)/10);b.style.filter=
"alpha(opacity="+(c+speed)+");";b.style.opacity=(c+speed)/100;100<=c&&clearInterval(d)},100)}var d=this,f=l(a.box),m=l(a.list),A=a.type||1,x=m.getElementsByTagName("img"),r=m.getElementsByTagName("a"),E=[],u=[],y=0,z="top",B="offsetTop",w=m.children,v=null,F=null,D=null,H=null,J=null,K=null,L=0,q=0,G=0,N=a.spacing||4E3,I=a.btnListClass,M=a.btnClass,C=a.showText;f.style.position="relative";m.style.position="relative";for(var t=0;t<x.length;t++)E.push(x[t].src);if(0<r.length)for(t=0;t<r.length;t++)u.push(r[t].href);
"top"===a.direction?(y=w[1].offsetTop-w[0].offsetTop,z="top",G=m.offsetTop,B="offsetTop"):(y=w[1].offsetLeft-w[0].offsetLeft,z="left",G=m.offsetLeft,B="offsetLeft");C&&c();(function(){var a="";v=document.createElement("ul");v.className=I;for(var b=0;b<w.length;b++)a+="<li>"+(b+1)+"</li>";v.innerHTML=a;v.children[0].className=M;f.appendChild(v)})();l(C)&&(L=l(C).offsetHeight);F=v.getElementsByTagName("li");for(t=0;t<F.length;t++)n(F[t],"click",function(a){return function(){clearInterval(H);k(a);h(A,
a);q=a;C&&b(q)}}(t));H=setInterval(function(){q=q>=w.length-1?0:++q;k(q);h(A,q);C&&b(q)},N);n(f,"mouseover",function(){clearInterval(H)});n(f,"mouseout",function(){H=setInterval(function(){q=q>=w.length-1?0:++q;k(q);h(A,q);C&&b(q)},N)})},foldMenu:function(a){var c=l(a.id),b=a.foldElement&&a.foldElement.toLowerCase()||"UL",k=a.foldChildElement||"LI",h=a.afterClassName,g=null;n(c,"click",function(a){e=window.event||a;for(a=e.srcElement||e.target;a.tagName!=k&&a!=c&&"BODY"!=a.tagName;)a=a.parentNode;
0<a.getElementsByTagName(b).length&&(a.getElementsByTagName(b)[0].style.display="block"===a.getElementsByTagName(b)[0].style.display?"none":"block",h)&&(g=eval("/(^"+h+")|((\\s)"+h+")/g"),"block"===a.getElementsByTagName(b)[0].style.display?a.className+=" "+h:a.className=a.className.replace(g,""))})}}})();